apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
spec:
  destination:
    name: ''
    namespace: keda
    server: 'https://kubernetes.default.svc'
  source:
    path: keda
    repoURL: 'https://github.com/maheshopsmx/testArgoProj.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
