apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    argocd.argoproj.io/instance: bookinfo-bl
  name: productpage
  namespace: bookinfo-bl
spec:
  cooldownPeriod: 300
  idleReplicaCount: 0
  maxReplicaCount: 1
  minReplicaCount: 1
  pollingInterval: 120
  scaleTargetRef:
    name: productpage
  triggers:
    - metadata:
        activationThreshold: '1.0'
        ignoreNullValues: 'true'
        metricName: nginx_ingress_controller_requests
        query: >-
          sum(rate(nginx_ingress_controller_requests{service="productpage",namespace="bookinfo-bl"}[2m]))*120
        serverAddress: 'http://prom-prometheus-server.maheshprom:80'
        threshold: '100.50'
      type: prometheus
