kustomize:
  images:
  - docker.io/opsmx11/oes-audit-client:argo-5e28642-48
  - docker.io/opsmx11/oes-audit-service:argo-16f08e7-11
  - docker.io/opsmx11/oes-platform:argo-3aae50c0-92
  - docker.io/opsmx11/oes-dashboard:argo-b363cb0-19
  - docker.io/opsmx11/oes-visibility:argo-42b5bae-8
  - docker.io/opsmx11/gate:argo-34980216-9
  - docker.io/opsmx11/sapor:argo-cb6f860e4615be6ffcbb57ab2cbccb398b203674-33
  - docker.io/opsmx11/oes-autopilot:argo-67c114a13-50
  - docker.io/opsmx11/oes-datascience:argo-beb86ec33f46e253de0107437c0625f0481147d5-8
