apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: productpage
    version: v5
spec:
  replicas: 0
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
        - name: productpage
          image: quay.io/opsmxpublic/productpage:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
