---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-411-sns 
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bookinfo-411-sns
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs/status
    verbs:
      - get
      - list
      - patch
  - apiGroups:	
      - ""	
    resources:	
      - pods	
    verbs:	
      - get	
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bookinfo-411-sns
subjects:
  - kind: ServiceAccount
    name: bookinfo-411-sns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bookinfo-411-sns
