kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: single-ns-analysis
spec:
  args:
    - name: preview-hash
    - name: baseline-hash
    - name: servicename
  metrics:
    - name: single-ns-analysis
      count: 1
      initialDelay: 120s
      provider:
        opsmx:
          application: APP-NAME
          user: admin
          lifetimeMinutes: 3
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: "{{args.servicename}}"
            metricTemplateName: prometheus-health-validator
            metricTemplateVersion: "v2.0"
            metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "APP-NS,.*{{args.baseline-hash}}.*,APP-LABEL" 
            canaryMetricScope: "APP-NS,.*{{args.preview-hash}}.*,APP-LABEL"
